"""
Configuration for Datasets
"""
import os


RAW_DATASET_FILENAME = "GrammarDataset.csv"
DATASET_FOLDER = "data"
RAW_DATASET_FOLDER = "raw"
PROCESSED_DATASET_FOLDER = "processed"
PROCESSED_DATASET_TRAIN_FILENAME = "test.tsv"
PROCESSED_DATASET_TEST_FILENAME = "train.tsv"
RAW_DATASET = os.path.join(DATASET_FOLDER, RAW_DATASET_FOLDER, RAW_DATASET_FILENAME)
PROCESSED_DATASET = {
    "train": os.path.join(
        DATASET_FOLDER, PROCESSED_DATASET_FOLDER, PROCESSED_DATASET_TRAIN_FILENAME
    ),
    "test": os.path.join(
        DATASET_FOLDER, PROCESSED_DATASET_FOLDER, PROCESSED_DATASET_TEST_FILENAME
    ),
}
